"""change file user_id to session_id

Revision ID: 6bf80b3f55e0
Revises: d5986159f1d9
Create Date: 2026-06-01 13:27:53.364715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bf80b3f55e0'
down_revision: Union[str, Sequence[str], None] = 'd5986159f1d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('session_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_files_user_id'), table_name='files')
    op.create_index(op.f('ix_files_session_id'), 'files', ['session_id'], unique=False)
    op.drop_constraint(op.f('files_user_id_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('files', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key(op.f('files_user_id_fkey'), 'files', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_files_session_id'), table_name='files')
    op.create_index(op.f('ix_files_user_id'), 'files', ['user_id'], unique=False)
    op.drop_column('files', 'session_id')
    # ### end Alembic commands ###
