"""remove status and ended_at from sessions

Revision ID: bef64fbb9802
Revises: 6bf80b3f55e0
Create Date: 2026-06-10 14:36:54.165892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bef64fbb9802'
down_revision: Union[str, Sequence[str], None] = '6bf80b3f55e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'ended_at')
    op.drop_column('sessions', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
